### ISSUE TITLE
Some small bugs

### ISSUE THREAD

**Issue by tbpoetke** [egidiusmengelberg/grandma2_colorpicker_plugin#1]
Hello Egidius, thx for sharing your work! I found two bugs: First, it looks like the order of the colors are confused. In your readme its Cyan, Blue, Lavender, but in the Layout its Cyan, Lavender, Blue.
And then I have another big Problem: In the Layout view the Pool Buttons haven´t loaded any Images, I have to add them manually, The switching of the images works fine then. Hopefully we will see an update!

**Comment by egidiusmengelberg** [comment]
Hello, thanks for sharing these bugs. I will fix these as soon as possible. The second one you talk about isn’t a bug. Grandma2 does not let you automatically set background images in layout  views. I searched half the internet to find a solution but I guess you still need to assign the images yourself. If anyone has a solution I would be happy to implement it. For now I will fix the typo in the readme. And tidy up the code.
