### ISSUE TITLE
Small bug

### ISSUE THREAD

**Issue by bjeffrey2492** [egidiusmengelberg/grandma2_colorpicker_plugin#2]
I'll poke around the code and try to find it but I'm a lua novice.   

The High/Low Executors with the commands to replace the color preset seem to be replacing to the same preset 4.112.       I believe one of them needs to be 4.113 or 4.112

**Comment by egidiusmengelberg** [comment]
That sounds great!

Yeah, I had that issue to. In the version of the plugin that I actually use I think I already fixed it. I will try to push that sometime this week. 

You could always make a pull request.

Kind regards,

Egidius Mengelberg

**Comment by bjeffrey2492** [comment]
Thanks for the quick reply.       

Whats a pull request?     New here......

**Comment by bjeffrey2492** [comment]
Ahhh.  I see.  Its a way to suggest edits.
