### ISSUE TITLE
Automatically add Pictures and change them on a click

### ISSUE THREAD

**Issue by Spacelord09** [egidiusmengelberg/grandma2_colorpicker_plugin#3]

**Comment by Spacelord09** [comment]
Here is a test showfile.
[colorpicker.show.gz](https://github.com/egidiusmengelberg/grandma2_colorpicker_plugin/files/3596179/colorpicker.show.gz)

**Comment by egidiusmengelberg** [comment]
Hi, 

I'm not really sure what your intentions are?
Your showfile seems empty and I do not know what you want by looking at the title of the issue.

An explanation would be great!

Kind regards,

Egidius Mengelberg

**Comment by Spacelord09** [comment]
Hello @egidiusmengelberg!

Your plugin creates a colorpicker in a layout view like Christian Jackson has in his showfiles.

But your "colorpicker" does not have a feedback in the layout window.
Do you understand my problem now?

**Comment by Spacelord09** [comment]
https://www.youtube.com/watch?v=0APXKkyCxmQ

**Comment by egidiusmengelberg** [comment]
I do not know what you mean by feedback. The filled in boxes when a color is selected? Because that works fine.

**Comment by Spacelord09** [comment]
Not for me... But I have found a solution.
