### ISSUE TITLE
grandma2_colorpicker_plugin/颜色选择器.xml

### ISSUE THREAD

**Issue by yukun2021** [egidiusmengelberg/grandma2_colorpicker_plugin#4]
Can I have this folder?grandma2

**Comment by egidiusmengelberg** [comment]
What do you mean?

**Comment by yukun2021** [comment]
Can you share this color picker file with me?


Google Cloud Disk or other、


I'm a stage lighting programmer.

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Egidius Mengelberg ***@***.***&gt;
发送时间: 2021年8月4日 23:52
收件人: egidiusmengelberg/grandma2_colorpicker_plugin ***@***.***&gt;
抄送: yukun ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[egidiusmengelberg/grandma2_colorpicker_plugin] grandma2_colorpicker_plugin/颜色选择器.xml (#4)

**Comment by Spacelord09** [comment]
Just download it from this repository🤣😅 

#INVALID
#CLOSE

**Comment by yukun2021** [comment]
I can't seem to download it from my phone.😂🤣



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Spacelord ***@***.***&gt;
发送时间: 2021年8月5日 12:49
收件人: egidiusmengelberg/grandma2_colorpicker_plugin ***@***.***&gt;
抄送: yukun ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[egidiusmengelberg/grandma2_colorpicker_plugin] grandma2_colorpicker_plugin/颜色选择器.xml (#4)





 
Just download it from this repository🤣😅
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Spacelord09** [comment]
Just use a computer.

**Comment by Spacelord09** [comment]
https://github.com/egidiusmengelberg/grandma2_colorpicker_plugin/archive/refs/heads/master.zip

**Comment by yukun2021** [comment]
Oh, thank you.

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Spacelord ***@***.***&gt;
发送时间: 2021年8月5日 13:33
收件人: egidiusmengelberg/grandma2_colorpicker_plugin ***@***.***&gt;
抄送: yukun ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[egidiusmengelberg/grandma2_colorpicker_plugin] grandma2_colorpicker_plugin/颜色选择器.xml (#4)





 
https://github.com/egidiusmengelberg/grandma2_colorpicker_plugin/archive/refs/heads/master.zip
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
